sudo: required
services:
  - docker
before_install:
  - docker build -t xavophonic/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true xavophonic/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-3-992382828808"
  bucket_path: "frontend"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"